apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poll-service
  template:
    metadata:
      labels:
        app: poll-service
    spec:
      containers:
        - name: poll-service
          image: ghcr.io/sympoll/poll-service/sympoll-poll-service:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://poll-db:5432/polldb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: poll-db-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: poll-service
spec:
  selector:
    app: poll-service
  ports:
    - protocol: TCP
      port: 8082
  type: ClusterIP
