version: "3.8"

services:
  poll-manager:
    image: ghcr.io/sympoll/poll-management-service/sympoll-poll-service:latest
    container_name: poll-manager
    ports:
      - "8081:8081"
    networks:
      - sympoll-network

  frontend:
    image: ghcr.io/sympoll/front-end-service/sympoll-front-end-test:latest
    container_name: frontend
    ports:
      - "80:8080"
    depends_on:
      - poll-manager
    networks:
      - sympoll-network

networks:
  sympoll-network:
    driver: bridge
