apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/sympoll/front-end-service/sympoll-front-end:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: frontend-config
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: frontend
  type: ClusterIP

---
apiVersion: v1
data:
  VITE_BASE_URL: http://localhost
  VITE_ENABLE_AUTH: auth-disabled
  VITE_KEYCLOAK_URL: https://auth.localhost
kind: ConfigMap
metadata:
  creationTimestamp: "2024-09-08T12:53:21Z"
  name: frontend-config
  namespace: default
  resourceVersion: "10952"
  uid: 5a8954a0-a007-4131-9eb4-c44493b52ffb
