apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/sympoll/front-end-service/sympoll-front-end-test:latest
          resources:
            requests:
              memory: "256Mi"
              cpu: "150m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          envFrom:
            - configMapRef:
                name: frontend-config
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: frontend
  type: ClusterIP

---
apiVersion: v1
data:
  VITE_BASE_URL: http://sympoll.ddns.net
  VITE_ENABLE_AUTH: auth-enabled
  VITE_KEYCLOAK_URL: http://auth-sympoll.ddns.net
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: default
