apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-reverse-proxy
  labels:
    app: auth-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-reverse-proxy
  template:
    metadata:
      labels:
        app: auth-reverse-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name auth.sympoll.ddns.net;

        location / {
            proxy_pass http://keycloak:8181; # Routes to Keycloak service internally
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: auth-reverse-proxy
  labels:
    app: auth-reverse-proxy
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: auth-reverse-proxy
  type: ClusterIP
