apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote-db
  name: vote-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-db
  template:
    metadata:
      labels:
        app: vote-db
    spec:
      containers:
        - image: postgres:16.2
          name: postgres
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 5434
          env:
            - name: PGPORT
              value: "5434"
            - name: POSTGRES_DB
              value: votedb
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: vote-db-secrets
            - name: PGDATA
              value: /var/lib/postgresql/data/vote
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: vote-db-data
            - mountPath: /docker-entrypoint-initdb.d
              name: vote-db-init-config
      volumes:
        - name: vote-db-data
          persistentVolumeClaim:
            claimName: vote-db-pvc
        - name: vote-db-init-config
          configMap:
            name: vote-db-init-config

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-db
  name: vote-db
spec:
  ports:
    - name: postgres
      port: 5434
      protocol: TCP
      targetPort: 5434
  selector:
    app: vote-db
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: vote-db-secrets
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM= # "postgres" encoded in base64

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vote-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "standard"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vote-db-init-config
data:
  init.sql: |
    CREATE TABLE votes
    (
        vote_id        UUID PRIMARY KEY,
        user_id        UUID NOT NULL,
        voting_item_id INT  NOT NULL,
        vote_datetime  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
